<?php

namespace Modules\Node\Constants\Comic;

class ManageComicNodeCodeConstants
{
    const MANAGE_COMIC = 'MANAGE_COMIC';
    const MANAGE_COMIC_READ = 'MANAGE_COMIC_READ';
    const MANAGE_COMIC_CREATE = 'MANAGE_COMIC_CREATE';
    const MANAGE_COMIC_UPDATE = 'MANAGE_COMIC_UPDATE';
    const MANAGE_COMIC_DELETE = 'MANAGE_COMIC_DELETE';
    const MANAGE_COMIC_EPISODE = 'MANAGE_COMIC_EPISODE';
    const MANAGE_COMIC_EPISODE_READ = 'MANAGE_COMIC_EPISODE_READ';
    const MANAGE_COMIC_EPISODE_CREATE = 'MANAGE_COMIC_EPISODE_CREATE';
    const MANAGE_COMIC_EPISODE_UPDATE = 'MANAGE_COMIC_EPISODE_UPDATE';
    const MANAGE_COMIC_EPISODE_DELETE = 'MANAGE_COMIC_EPISODE_DELETE';
}
