<?php
/**
 * Created by PhpStorm.
 * User: derek
 * Date: 2020/2/10
 * Time: 下午 02:18
 */

namespace Modules\Node\Constants\FeatureFilm;

class AVActressSettingNodeCodeConstants
{
    const FEATURE_FILM_AV_ACTRESS_SETTING = 'FEATURE_FILM_AV_ACTRESS_SETTING';
    const FEATURE_FILM_AV_ACTRESS_SETTING_READ = 'FEATURE_FILM_AV_ACTRESS_SETTING_READ';
    const FEATURE_FILM_AV_ACTRESS_SETTING_CREATE = 'FEATURE_FILM_AV_ACTRESS_SETTING_CREATE';
    const FEATURE_FILM_AV_ACTRESS_SETTING_UPDATE = 'FEATURE_FILM_AV_ACTRESS_SETTING_UPDATE';
    const FEATURE_FILM_AV_ACTRESS_SETTING_DELETE = 'FEATURE_FILM_AV_ACTRESS_SETTING_DELETE';
}
