<?php
/**
 * Created by PhpStorm.
 * User: derek
 * Date: 2020/2/7
 * Time: 下午 12:03
 */

namespace Modules\Node\Constants\FeatureFilm;

class CupSettingNodeCodeConstants
{
    const FEATURE_FILM_CUP_SETTING = 'FEATURE_FILM_CUP_SETTING';
    const FEATURE_FILM_CUP_SETTING_READ = 'FEATURE_FILM_CUP_SETTING_READ';
    const FEATURE_FILM_CUP_SETTING_CREATE = 'FEATURE_FILM_CUP_SETTING_CREATE';
    const FEATURE_FILM_CUP_SETTING_UPDATE = 'FEATURE_FILM_CUP_SETTING_UPDATE';
    const FEATURE_FILM_CUP_SETTING_DELETE = 'FEATURE_FILM_CUP_SETTING_DELETE';
}
