<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 2020/2/3
 * Time: 下午 01:27
 */

namespace Modules\Node\Constants\FeatureFilm;

class GenresSettingNodeCodeConstants
{
    const FEATURE_FILM_GENRES_SETTING = 'FEATURE_FILM_GENRES_SETTING';
    const FEATURE_FILM_GENRES_SETTING_READ = 'FEATURE_FILM_GENRES_SETTING_READ';
    const FEATURE_FILM_GENRES_SETTING_CREATE = 'FEATURE_FILM_GENRES_SETTING_CREATE';
    const FEATURE_FILM_GENRES_SETTING_UPDATE = 'FEATURE_FILM_GENRES_SETTING_UPDATE';
    const FEATURE_FILM_GENRES_SETTING_DELETE = 'FEATURE_FILM_GENRES_SETTING_DELETE';
}

