<?php
/**
 * Created by PhpStorm.
 * User: derek
 * Date: 2020/2/4
 * Time: 下午 02:43
 */

namespace Modules\Node\Constants\FeatureFilm;

class RegionSettingNodeCodeConstants
{
    const FEATURE_FILM_REGION_SETTING = 'FEATURE_FILM_REGION_SETTING';
    const FEATURE_FILM_REGION_SETTING_READ = 'FEATURE_FILM_REGION_SETTING_READ';
    const FEATURE_FILM_REGION_SETTING_CREATE = 'FEATURE_FILM_REGION_SETTING_CREATE';
    const FEATURE_FILM_REGION_SETTING_UPDATE = 'FEATURE_FILM_REGION_SETTING_UPDATE';
    const FEATURE_FILM_REGION_SETTING_DELETE = 'FEATURE_FILM_REGION_SETTING_DELETE';
}
