<?php
/**
 * Created by PhpStorm.
 * User: funny
 * Date: 2020/1/31
 * Time: 下午 03:54
 */

namespace Modules\Node\Constants\FeatureFilm;

class YearsSettingNodeCodeConstants
{
    const FEATURE_FILM_YEARS_SETTING = 'FEATURE_FILM_YEARS_SETTING';
    const FEATURE_FILM_YEARS_SETTING_READ = 'FEATURE_FILM_YEARS_SETTING_READ';
    const FEATURE_FILM_YEARS_SETTING_CREATE = 'FEATURE_FILM_YEARS_SETTING_CREATE';
    const FEATURE_FILM_YEARS_SETTING_UPDATE = 'FEATURE_FILM_YEARS_SETTING_UPDATE';
    const FEATURE_FILM_YEARS_SETTING_DELETE = 'FEATURE_FILM_YEARS_SETTING_DELETE';
}
