<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 2020/2/4
 * Time: 上午 10:15
 */

namespace Modules\Node\Constants\Literature;

class GenresSettingNodeCodeConstants
{
    const LITERATURE_GENRES_SETTING = 'LITERATURE_GENRES_SETTING';
    const LITERATURE_GENRES_SETTING_READ = 'LITERATURE_GENRES_SETTING_READ';
    const LITERATURE_GENRES_SETTING_CREATE = 'LITERATURE_GENRES_SETTING_CREATE';
    const LITERATURE_GENRES_SETTING_UPDATE = 'LITERATURE_GENRES_SETTING_UPDATE';
    const LITERATURE_GENRES_SETTING_DELETE = 'LITERATURE_GENRES_SETTING_DELETE';
}
