<?php
/**
 * Created by PhpStorm.
 * User: derek
 * Date: 2020/2/5
 * Time: 下午 07:35
 */

namespace Modules\Node\Constants\Literature;

class RegionSettingNodeCodeConstants
{
    const LITERATURE_REGION_SETTING = 'LITERATURE_REGION_SETTING';
    const LITERATURE_REGION_SETTING_READ = 'LITERATURE_REGION_SETTING_READ';
    const LITERATURE_REGION_SETTING_CREATE = 'LITERATURE_REGION_SETTING_CREATE';
    const LITERATURE_REGION_SETTING_UPDATE = 'LITERATURE_REGION_SETTING_UPDATE';
    const LITERATURE_REGION_SETTING_DELETE = 'LITERATURE_REGION_SETTING_DELETE';
}
