<?php
/**
 * Created by PhpStorm.
 * User: funny
 * Date: 2020/1/31
 * Time: 下午 07:30
 */

namespace Modules\Node\Constants\Literature;

class YearsSettingNodeCodeConstants
{
    const LITERATURE_YEARS_SETTING = 'LITERATURE_YEARS_SETTING';
    const LITERATURE_YEARS_SETTING_READ = 'LITERATURE_YEARS_SETTING_READ';
    const LITERATURE_YEARS_SETTING_CREATE = 'LITERATURE_YEARS_SETTING_CREATE';
    const LITERATURE_YEARS_SETTING_UPDATE = 'LITERATURE_YEARS_SETTING_UPDATE';
    const LITERATURE_YEARS_SETTING_DELETE = 'LITERATURE_YEARS_SETTING_DELETE';
}
