<?php
/**
 * Created by PhpStorm.
 * User: derek
 * Date: 2020/3/4
 * Time: 下午 06:55
 */

namespace Modules\Node\Constants\Video;

class AdultVideoBucketNodeCodeConstants
{
    const VIDEO_ADULT_VIDEO_BUCKET_MANAGE = 'VIDEO_ADULT_VIDEO_BUCKET_MANAGE';
    const VIDEO_ADULT_VIDEO_BUCKET_MANAGE_READ = 'VIDEO_ADULT_VIDEO_BUCKET_MANAGE_READ';
    const VIDEO_ADULT_VIDEO_BUCKET_MANAGE_CREATE = 'VIDEO_ADULT_VIDEO_BUCKET_MANAGE_CREATE';
    const VIDEO_ADULT_VIDEO_BUCKET_MANAGE_UPDATE = 'VIDEO_ADULT_VIDEO_BUCKET_MANAGE_UPDATE';
}
