<?php
/**
 * Created by PhpStorm.
 * User: derek
 * Date: 2020/2/10
 * Time: 下午 04:38
 */

namespace Modules\Node\Constants\Video;

class AVActressSettingNodeCodeConstants
{
    const VIDEO_AV_ACTRESS_SETTING = 'VIDEO_AV_ACTRESS_SETTING';
    const VIDEO_AV_ACTRESS_SETTING_READ = 'VIDEO_AV_ACTRESS_SETTING_READ';
    const VIDEO_AV_ACTRESS_SETTING_CREATE = 'VIDEO_AV_ACTRESS_SETTING_CREATE';
    const VIDEO_AV_ACTRESS_SETTING_UPDATE = 'VIDEO_AV_ACTRESS_SETTING_UPDATE';
    const VIDEO_AV_ACTRESS_SETTING_DELETE = 'VIDEO_AV_ACTRESS_SETTING_DELETE';
}
