<?php

namespace Modules\Node\Constants\Movie;

class ManageMovieNodeCodeConstants
{
    const MANAGE_MOVIE = 'MANAGE_MOVIE';
    const MANAGE_MOVIE_READ = 'MANAGE_MOVIE_READ';
    const MANAGE_MOVIE_CREATE = 'MANAGE_MOVIE_CREATE';
    const MANAGE_MOVIE_UPDATE = 'MANAGE_MOVIE_UPDATE';
    const MANAGE_MOVIE_DELETE = 'MANAGE_MOVIE_DELETE';
    const MANAGE_MOVIE_EPISODE = 'MANAGE_MOVIE_EPISODE';
    const MANAGE_MOVIE_EPISODE_READ = 'MANAGE_MOVIE_EPISODE_READ';
    const MANAGE_MOVIE_EPISODE_CREATE = 'MANAGE_MOVIE_EPISODE_CREATE';
    const MANAGE_MOVIE_EPISODE_UPDATE = 'MANAGE_MOVIE_EPISODE_UPDATE';
    const MANAGE_MOVIE_EPISODE_DELETE = 'MANAGE_MOVIE_EPISODE_DELETE';
}
