<?php
/**
 * Created by PhpStorm.
 * User: derek
 * Date: 2020/2/10
 * Time: 下午 04:14
 */

namespace Modules\Node\Constants\Photograph;

class AVActressSettingNodeCodeConstants
{
    const PHOTOGRAPH_AV_ACTRESS_SETTING = 'PHOTOGRAPH_AV_ACTRESS_SETTING';
    const PHOTOGRAPH_AV_ACTRESS_SETTING_READ = 'PHOTOGRAPH_AV_ACTRESS_SETTING_READ';
    const PHOTOGRAPH_AV_ACTRESS_SETTING_CREATE = 'PHOTOGRAPH_AV_ACTRESS_SETTING_CREATE';
    const PHOTOGRAPH_AV_ACTRESS_SETTING_UPDATE = 'PHOTOGRAPH_AV_ACTRESS_SETTING_UPDATE';
    const PHOTOGRAPH_AV_ACTRESS_SETTING_DELETE = 'PHOTOGRAPH_AV_ACTRESS_SETTING_DELETE';
}
