<?php
/**
 * Created by PhpStorm.
 * User: derek
 * Date: 2020/2/7
 * Time: 下午 03:30
 */

namespace Modules\Node\Constants\Photograph;

class CupSettingNodeCodeConstants
{
    const PHOTOGRAPH_CUP_SETTING = 'PHOTOGRAPH_CUP_SETTING';
    const PHOTOGRAPH_CUP_SETTING_READ = 'PHOTOGRAPH_CUP_SETTING_READ';
    const PHOTOGRAPH_CUP_SETTING_CREATE = 'PHOTOGRAPH_CUP_SETTING_CREATE';
    const PHOTOGRAPH_CUP_SETTING_UPDATE = 'PHOTOGRAPH_CUP_SETTING_UPDATE';
    const PHOTOGRAPH_CUP_SETTING_DELETE = 'PHOTOGRAPH_CUP_SETTING_DELETE';
}
