<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 2020/2/3
 * Time: 下午 05:10
 */

namespace Modules\Node\Constants\Photograph;

class GenresSettingNodeCodeConstants
{
    const PHOTOGRAPH_GENRES_SETTING = 'PHOTOGRAPH_GENRES_SETTING';
    const PHOTOGRAPH_GENRES_SETTING_READ = 'PHOTOGRAPH_GENRES_SETTING_READ';
    const PHOTOGRAPH_GENRES_SETTING_CREATE = 'PHOTOGRAPH_GENRES_SETTING_CREATE';
    const PHOTOGRAPH_GENRES_SETTING_UPDATE = 'PHOTOGRAPH_GENRES_SETTING_UPDATE';
    const PHOTOGRAPH_GENRES_SETTING_DELETE = 'PHOTOGRAPH_GENRES_SETTING_DELETE';
}
