<?php
/**
 * Created by PhpStorm.
 * User: derek
 * Date: 2020/2/4
 * Time: 下午 07:01
 */

namespace Modules\Node\Constants\Photograph;

class RegionSettingNodeCodeConstants
{
    const PHOTOGRAPH_REGION_SETTING = 'PHOTOGRAPH_REGION_SETTING';
    const PHOTOGRAPH_REGION_SETTING_READ = 'PHOTOGRAPH_REGION_SETTING_READ';
    const PHOTOGRAPH_REGION_SETTING_CREATE = 'PHOTOGRAPH_REGION_SETTING_CREATE';
    const PHOTOGRAPH_REGION_SETTING_UPDATE = 'PHOTOGRAPH_REGION_SETTING_UPDATE';
    const PHOTOGRAPH_REGION_SETTING_DELETE = 'PHOTOGRAPH_REGION_SETTING_DELETE';
}
