<?php
/**
 * Created by PhpStorm.
 * User: funny
 * Date: 2020/1/31
 * Time: 下午 05:50
 */

namespace Modules\Node\Constants\Photograph;

class YearsSettingNodeCodeConstants
{
    const PHOTOGRAPH_YEARS_SETTING = 'PHOTOGRAPH_YEARS_SETTING';
    const PHOTOGRAPH_YEARS_SETTING_READ = 'PHOTOGRAPH_YEARS_SETTING_READ';
    const PHOTOGRAPH_YEARS_SETTING_CREATE = 'PHOTOGRAPH_YEARS_SETTING_CREATE';
    const PHOTOGRAPH_YEARS_SETTING_UPDATE = 'PHOTOGRAPH_YEARS_SETTING_UPDATE';
    const PHOTOGRAPH_YEARS_SETTING_DELETE = 'PHOTOGRAPH_YEARS_SETTING_DELETE';
}
