<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 2020/2/4
 * Time: 上午 11:06
 */

namespace Modules\Node\Constants\Storytelling;

class GenresSettingNodeCodeConstants
{
    const STORYTELLING_GENRES_SETTING = 'STORYTELLING_GENRES_SETTING';
    const STORYTELLING_GENRES_SETTING_READ = 'STORYTELLING_GENRES_SETTING_READ';
    const STORYTELLING_GENRES_SETTING_CREATE = 'STORYTELLING_GENRES_SETTING_CREATE';
    const STORYTELLING_GENRES_SETTING_UPDATE = 'STORYTELLING_GENRES_SETTING_UPDATE';
    const STORYTELLING_GENRES_SETTING_DELETE = 'STORYTELLING_GENRES_SETTING_DELETE';
}

