<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 2020/3/11
 * Time: 下午 04:43
 */

namespace Modules\Node\Constants\Storytelling;

class ManageStorytellingNodeCodeConstants
{
    const MANAGE_STORYTELLING = 'MANAGE_STORYTELLING';
    const MANAGE_STORYTELLING_READ = 'MANAGE_STORYTELLING_READ';
    const MANAGE_STORYTELLING_CREATE = 'MANAGE_STORYTELLING_CREATE';
    const MANAGE_STORYTELLING_UPDATE = 'MANAGE_STORYTELLING_UPDATE';
    const MANAGE_STORYTELLING_DELETE = 'MANAGE_STORYTELLING_DELETE';
    const MANAGE_STORYTELLING_AUDIO = 'MANAGE_STORYTELLING_AUDIO';
    const MANAGE_STORYTELLING_AUDIO_READ = 'MANAGE_STORYTELLING_AUDIO_READ';
    const MANAGE_STORYTELLING_AUDIO_CREATE = 'MANAGE_STORYTELLING_AUDIO_CREATE';
    const MANAGE_STORYTELLING_AUDIO_DELETE = 'MANAGE_STORYTELLING_AUDIO_DELETE';
}

