<?php
/**
 * Created by PhpStorm.
 * User: derek
 * Date: 2020/2/6
 * Time: 上午 11:45
 */

namespace Modules\Node\Constants\Storytelling;

class RegionSettingNodeCodeConstants
{
    const STORYTELLING_REGION_SETTING = 'STORYTELLING_REGION_SETTING';
    const STORYTELLING_REGION_SETTING_READ = 'STORYTELLING_REGION_SETTING_READ';
    const STORYTELLING_REGION_SETTING_CREATE = 'STORYTELLING_REGION_SETTING_CREATE';
    const STORYTELLING_REGION_SETTING_UPDATE = 'STORYTELLING_REGION_SETTING_UPDATE';
    const STORYTELLING_REGION_SETTING_DELETE = 'STORYTELLING_REGION_SETTING_DELETE';
}
