<?php
/**
 * Created by PhpStorm.
 * User: funny
 * Date: 2020/2/3
 * Time: 上午 11:21
 */

namespace Modules\Node\Constants\Storytelling;

class YearsSettingNodeCodeConstants
{
    const STORYTELLING_YEARS_SETTING = 'STORYTELLING_YEARS_SETTING';
    const STORYTELLING_YEARS_SETTING_READ = 'STORYTELLING_YEARS_SETTING_READ';
    const STORYTELLING_YEARS_SETTING_CREATE = 'STORYTELLING_YEARS_SETTING_CREATE';
    const STORYTELLING_YEARS_SETTING_UPDATE = 'STORYTELLING_YEARS_SETTING_UPDATE';
    const STORYTELLING_YEARS_SETTING_DELETE = 'STORYTELLING_YEARS_SETTING_DELETE';
}
