<?php
/**
 * Created by PhpStorm.
 * User: derek
 * Date: 2020/2/10
 * Time: 下午 03:35
 */

namespace Modules\Node\Constants\ShortFilm;

class AVActressSettingNodeCodeConstants
{
    const SHORT_FILM_AV_ACTRESS_SETTING = 'SHORT_FILM_AV_ACTRESS_SETTING';
    const SHORT_FILM_AV_ACTRESS_SETTING_READ = 'SHORT_FILM_AV_ACTRESS_SETTING_READ';
    const SHORT_FILM_AV_ACTRESS_SETTING_CREATE = 'SHORT_FILM_AV_ACTRESS_SETTING_CREATE';
    const SHORT_FILM_AV_ACTRESS_SETTING_UPDATE = 'SHORT_FILM_AV_ACTRESS_SETTING_UPDATE';
    const SHORT_FILM_AV_ACTRESS_SETTING_DELETE = 'SHORT_FILM_AV_ACTRESS_SETTING_DELETE';
}
