<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 2020/2/14
 * Time: 下午 04:57
 */

namespace Modules\Node\Constants\Anime;

class ManageAnimeNodeCodeConstants
{
    const MANAGE_ANIME = 'MANAGE_ANIME';
    const MANAGE_ANIME_READ = 'MANAGE_ANIME_READ';
    const MANAGE_ANIME_CREATE = 'MANAGE_ANIME_CREATE';
    const MANAGE_ANIME_UPDATE = 'MANAGE_ANIME_UPDATE';
    const MANAGE_ANIME_DELETE = 'MANAGE_ANIME_DELETE';
    const MANAGE_ANIME_EPISODE = 'MANAGE_ANIME_EPISODE';
    const MANAGE_ANIME_EPISODE_READ = 'MANAGE_ANIME_EPISODE_READ';
    const MANAGE_ANIME_EPISODE_CREATE = 'MANAGE_ANIME_EPISODE_CREATE';
    const MANAGE_ANIME_EPISODE_UPDATE = 'MANAGE_ANIME_EPISODE_UPDATE';
    const MANAGE_ANIME_EPISODE_DELETE = 'MANAGE_ANIME_EPISODE_DELETE';
}
