<?php
/**
 * Created by PhpStorm.
 * User: funny
 * Date: 2020/2/14
 * Time: 下午 07:22
 */

namespace Modules\Node\Constants\Drama;

class ManageDramaNodeCodeConstants
{
    const MANAGE_DRAMA = 'MANAGE_DRAMA';
    const MANAGE_DRAMA_READ = 'MANAGE_DRAMA_READ';
    const MANAGE_DRAMA_CREATE = 'MANAGE_DRAMA_CREATE';
    const MANAGE_DRAMA_UPDATE = 'MANAGE_DRAMA_UPDATE';
    const MANAGE_DRAMA_DELETE = 'MANAGE_DRAMA_DELETE';
    const MANAGE_DRAMA_EPISODE = 'MANAGE_DRAMA_EPISODE';
    const MANAGE_DRAMA_EPISODE_READ = 'MANAGE_DRAMA_EPISODE_READ';
    const MANAGE_DRAMA_EPISODE_CREATE = 'MANAGE_DRAMA_EPISODE_CREATE';
    const MANAGE_DRAMA_EPISODE_UPDATE = 'MANAGE_DRAMA_EPISODE_UPDATE';
    const MANAGE_DRAMA_EPISODE_DELETE = 'MANAGE_DRAMA_EPISODE_DELETE';
}
