<?php
/**
 * Created by PhpStorm.
 * User: USER
 * Date: 2018/7/20
 * Time: 下午 04:01
 */

namespace Modules\Node\Constants;

/**
 * Class NodePathConstants handle node path declare.
 * @package Modules\Node\Constants
 */
class NodeCodeConstants
{
    const ACCOUNT_MANAGE = 'ACCOUNT_MANAGE';
    const ACCOUNT_MANAGE_READ = 'ACCOUNT_MANAGE_READ';
    const ACCOUNT_MANAGE_CREATE = 'ACCOUNT_MANAGE_CREATE';
    const ACCOUNT_MANAGE_UPDATE = 'ACCOUNT_MANAGE_UPDATE';
    const ACCOUNT_MANAGE_DELETE = 'ACCOUNT_MANAGE_DELETE';
    const ROLE_CUSTOM_MANAGE = 'ROLE_CUSTOM_MANAGE';
    const ROLE_CUSTOM_MANAGE_READ = 'ROLE_CUSTOM_MANAGE_READ';
    const ROLE_CUSTOM_MANAGE_CREATE = 'ROLE_CUSTOM_MANAGE_CREATE';
    const ROLE_CUSTOM_MANAGE_UPDATE = 'ROLE_CUSTOM_MANAGE_UPDATE';
    const ROLE_CUSTOM_MANAGE_DELETE = 'ROLE_CUSTOM_MANAGE_DELETE';
    const ROLE_PUBLIC_AUTHORIZATION = 'ROLE_PUBLIC_AUTHORIZATION';
    const ROLE_PUBLIC_AUTHORIZATION_READ = 'ROLE_PUBLIC_AUTHORIZATION_READ';
    const ACCOUNT_LOGIN_HISTORY = 'ACCOUNT_LOGIN_HISTORY';
    const ACCOUNT_LOGIN_HISTORY_READ = 'ACCOUNT_LOGIN_HISTORY_READ';
    const MANAGE_BRANCH = 'MANAGE_BRANCH';
    const MANAGE_BRANCH_READ = 'MANAGE_BRANCH_READ';
    const MANAGE_BRANCH_CREATE = 'MANAGE_BRANCH_CREATE';
    const MANAGE_BRANCH_UPDATE = 'MANAGE_BRANCH_UPDATE';
    const MANAGE_BRANCH_DELETE = 'MANAGE_BRANCH_DELETE';
    const MANAGE_ANNOUNCEMENT = 'MANAGE_ANNOUNCEMENT';
    const MANAGE_ANNOUNCEMENT_READ = 'MANAGE_ANNOUNCEMENT_READ';
    const MANAGE_ANNOUNCEMENT_CREATE = 'MANAGE_ANNOUNCEMENT_CREATE';
    const MANAGE_ANNOUNCEMENT_UPDATE = 'MANAGE_ANNOUNCEMENT_UPDATE';
    const MANAGE_ANNOUNCEMENT_DELETE = 'MANAGE_ANNOUNCEMENT_DELETE';
    const MANAGE_ADVERTISEMENT = 'MANAGE_ADVERTISEMENT';
    const MANAGE_ADVERTISEMENT_READ = 'MANAGE_ADVERTISEMENT_READ';
    const MANAGE_ADVERTISEMENT_CREATE = 'MANAGE_ADVERTISEMENT_CREATE';
    const MANAGE_ADVERTISEMENT_UPDATE = 'MANAGE_ADVERTISEMENT_UPDATE';
    const MANAGE_ADVERTISEMENT_DELETE = 'MANAGE_ADVERTISEMENT_DELETE';
    const MANAGE_MEMBER = 'MANAGE_MEMBER';
    const MANAGE_MEMBER_READ = 'MANAGE_MEMBER_READ';
    const MANAGE_MEMBER_CREATE = 'MANAGE_MEMBER_CREATE';
    const MANAGE_MEMBER_UPDATE = 'MANAGE_MEMBER_UPDATE';
    const MANAGE_MEMBER_DELETE = 'MANAGE_MEMBER_DELETE';
    const MEMBER_LOGIN_HISTORY = 'MEMBER_LOGIN_HISTORY';
    const MEMBER_LOGIN_HISTORY_READ = 'MEMBER_LOGIN_HISTORY_READ';
}
