<?php
/**
 * Created by PhpStorm.
 * User: user
 * Date: 2020/2/3
 * Time: 上午 11:33
 */

namespace Modules\Node\Constants\Variety;

class GenresSettingNodeCodeConstants
{
    const VARIETY_GENRES_SETTING = 'VARIETY_GENRES_SETTING';
    const VARIETY_GENRES_SETTING_READ = 'VARIETY_GENRES_SETTING_READ';
    const VARIETY_GENRES_SETTING_CREATE = 'VARIETY_GENRES_SETTING_CREATE';
    const VARIETY_GENRES_SETTING_UPDATE = 'VARIETY_GENRES_SETTING_UPDATE';
    const VARIETY_GENRES_SETTING_DELETE = 'VARIETY_GENRES_SETTING_DELETE';
}
