<?php
/**
 * Created by PhpStorm.
 * User: funny
 * Date: 2020/2/17
 * Time: 下午 06:43
 */

namespace Modules\Node\Constants\Variety;

class ManageVarietyNodeCodeConstants
{
    const MANAGE_VARIETY = 'MANAGE_VARIETY';
    const MANAGE_VARIETY_READ = 'MANAGE_VARIETY_READ';
    const MANAGE_VARIETY_CREATE = 'MANAGE_VARIETY_CREATE';
    const MANAGE_VARIETY_UPDATE = 'MANAGE_VARIETY_UPDATE';
    const MANAGE_VARIETY_DELETE = 'MANAGE_VARIETY_DELETE';
    const MANAGE_VARIETY_EPISODE = 'MANAGE_VARIETY_EPISODE';
    const MANAGE_VARIETY_EPISODE_READ = 'MANAGE_VARIETY_EPISODE_READ';
    const MANAGE_VARIETY_EPISODE_CREATE = 'MANAGE_VARIETY_EPISODE_CREATE';
    const MANAGE_VARIETY_EPISODE_UPDATE = 'MANAGE_VARIETY_EPISODE_UPDATE';
    const MANAGE_VARIETY_EPISODE_DELETE = 'MANAGE_VARIETY_EPISODE_DELETE';
}
